name: bacdive-interface
channels:
  - defaults
  - conda-forge
dependencies:
  - blinker=1.9.0=pyhff2d567_0
  - bottleneck=1.4.2=py311hb9f6ed7_0
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.7.15=hca03da5_0
  - certifi=2025.8.3=py311hca03da5_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=pyh707e725_0
  - contourpy=1.3.2=py311h210dab8_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - flask=3.1.1=pyhd8ed1ab_0
  - fonttools=4.58.0=py311h4921393_0
  - freetype=2.13.3=hce30654_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py311h2c37856_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=20.1.5=ha82da77_0
  - libdeflate=1.24=h5773f1b_0
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblzma=5.8.1=h39f12f2_1
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - libsqlite=3.49.2=h3f77e49_0
  - libtiff=4.7.0=h2f21f7c_5
  - libuuid=1.41.5=h80987f9_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.5=hdb05f8b_0
  - markupsafe=3.0.2=py311h4921393_1
  - matplotlib=3.10.3=py311ha1ab1f8_0
  - matplotlib-base=3.10.3=py311h031da69_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h5e97a16_3
  - numexpr=2.11.0=py311h8c72970_1
  - numpy=2.2.6=py311h762c074_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.5.0=h81ee809_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py311h43d6402_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.2.1=py311hb9ba9e9_0
  - pip=25.1.1=pyh8b19718_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.12=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - request=2.83.1=0
  - requests=2.32.3=py311hca03da5_1
  - scipy=1.15.2=py311h0675101_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - statsmodels=0.14.4=py311h0f07fe1_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.5.1=py311h917b07b_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py311h917b07b_0
  - urllib3=2.3.0=py311hca03da5_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - distro==1.9.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - jiter==0.10.0
      - openai==1.82.0
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - rdflib==7.1.4
      - sniffio==1.3.1
      - sparqlwrapper==2.0.0
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
prefix: /Users/marcoanteghini/miniforge3/envs/bacdive-interface
